package frontend

import "embed"

// Files contains the production frontend bundle. The bundle is generated by
// `npm --prefix frontend run build` before Go/Wails packaging.
//
//go:embed dist
var Files embed.FS
