// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {filesystem} from '../models';
import {project} from '../models';
import {app} from '../models';
import {config} from '../models';
import {git} from '../models';

export function BrowseProject(arg1:string,arg2:string):Promise<Array<filesystem.Entry>>;

export function CancelAgent(arg1:string):Promise<boolean>;

export function Capabilities():Promise<Array<project.Capability>>;

export function CreateSession(arg1:string,arg2:string,arg3:string,arg4:string):Promise<app.SessionDTO>;

export function CheckoutGitBranch(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function CreateGitWorktree(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function DeleteGitBranch(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function GetTurnChanges(arg1:string):Promise<Array<app.FileChangeDTO>>;

export function GitBranches(arg1:string):Promise<git.BranchSnapshot>;

export function Health():Promise<app.HealthResponse>;

export function ListProjects():Promise<Array<app.ProjectDTO>>;

export function ListSessions(arg1:string):Promise<Array<app.SessionDTO>>;

export function LoadConversation(arg1:string):Promise<app.ConversationSnapshotDTO>;

export function OpenProject(arg1:string):Promise<app.ProjectDTO>;

export function RenameSession(arg1:string,arg2:string):Promise<void>;

export function ResolveApproval(arg1:app.ApprovalResolution):Promise<void>;

export function SendMessage(arg1:string,arg2:string,arg3:string,arg4:string):Promise<app.AgentTurnDTO>;

export function SelectDirectory(arg1:string):Promise<string>;

export function Settings():Promise<config.Config>;

export function UpdateSettings(arg1:app.SettingsUpdate):Promise<config.Config>;

export function UndoTurn(arg1:string):Promise<void>;
