// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseProject(arg1, arg2) {
  return window['go']['app']['RPCService']['BrowseProject'](arg1, arg2);
}

export function CancelAgent(arg1) {
  return window['go']['app']['RPCService']['CancelAgent'](arg1);
}

export function Capabilities() {
  return window['go']['app']['RPCService']['Capabilities']();
}

export function CheckoutGitBranch(arg1, arg2, arg3) {
  return window['go']['app']['RPCService']['CheckoutGitBranch'](arg1, arg2, arg3);
}

export function ConnectMCPServer(arg1) {
  return window['go']['app']['RPCService']['ConnectMCPServer'](arg1);
}

export function CreateGitWorktree(arg1, arg2, arg3, arg4) {
  return window['go']['app']['RPCService']['CreateGitWorktree'](arg1, arg2, arg3, arg4);
}

export function CreateSession(arg1, arg2, arg3, arg4) {
  return window['go']['app']['RPCService']['CreateSession'](arg1, arg2, arg3, arg4);
}

export function DeleteGitBranch(arg1, arg2, arg3) {
  return window['go']['app']['RPCService']['DeleteGitBranch'](arg1, arg2, arg3);
}

export function DeleteMCPServer(arg1) {
  return window['go']['app']['RPCService']['DeleteMCPServer'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['app']['RPCService']['DeleteProject'](arg1);
}

export function DisconnectMCPServer(arg1) {
  return window['go']['app']['RPCService']['DisconnectMCPServer'](arg1);
}

export function GetTurnChanges(arg1) {
  return window['go']['app']['RPCService']['GetTurnChanges'](arg1);
}

export function GitBranches(arg1) {
  return window['go']['app']['RPCService']['GitBranches'](arg1);
}

export function Health() {
  return window['go']['app']['RPCService']['Health']();
}

export function ListProjects() {
  return window['go']['app']['RPCService']['ListProjects']();
}

export function ListRecentSessions() {
  return window['go']['app']['RPCService']['ListRecentSessions']();
}

export function ListSessions(arg1) {
  return window['go']['app']['RPCService']['ListSessions'](arg1);
}

export function LoadConversation(arg1) {
  return window['go']['app']['RPCService']['LoadConversation'](arg1);
}

export function MCPServers() {
  return window['go']['app']['RPCService']['MCPServers']();
}

export function ModelProfiles() {
  return window['go']['app']['RPCService']['ModelProfiles']();
}

export function MoveSession(arg1, arg2) {
  return window['go']['app']['RPCService']['MoveSession'](arg1, arg2);
}

export function OpenProject(arg1) {
  return window['go']['app']['RPCService']['OpenProject'](arg1);
}

export function RenameProject(arg1, arg2) {
  return window['go']['app']['RPCService']['RenameProject'](arg1, arg2);
}

export function RenameSession(arg1, arg2) {
  return window['go']['app']['RPCService']['RenameSession'](arg1, arg2);
}

export function ResolveApproval(arg1) {
  return window['go']['app']['RPCService']['ResolveApproval'](arg1);
}

export function RevealProject(arg1) {
  return window['go']['app']['RPCService']['RevealProject'](arg1);
}

export function SaveMCPServer(arg1) {
  return window['go']['app']['RPCService']['SaveMCPServer'](arg1);
}

export function SaveModelProfile(arg1) {
  return window['go']['app']['RPCService']['SaveModelProfile'](arg1);
}

export function SelectDirectory(arg1) {
  return window['go']['app']['RPCService']['SelectDirectory'](arg1);
}

export function SelectModelProfile(arg1) {
  return window['go']['app']['RPCService']['SelectModelProfile'](arg1);
}

export function SendMessage(arg1, arg2, arg3, arg4) {
  return window['go']['app']['RPCService']['SendMessage'](arg1, arg2, arg3, arg4);
}

export function SetProjectPinned(arg1, arg2) {
  return window['go']['app']['RPCService']['SetProjectPinned'](arg1, arg2);
}

export function Settings() {
  return window['go']['app']['RPCService']['Settings']();
}

export function TestModelConnection(arg1) {
  return window['go']['app']['RPCService']['TestModelConnection'](arg1);
}

export function UndoTurn(arg1) {
  return window['go']['app']['RPCService']['UndoTurn'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['app']['RPCService']['UpdateSettings'](arg1);
}
