// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseProject(arg1, arg2) {
  return window['go']['app']['RPCService']['BrowseProject'](arg1, arg2);
}

export function CancelAgent(arg1) {
  return window['go']['app']['RPCService']['CancelAgent'](arg1);
}

export function Capabilities() {
  return window['go']['app']['RPCService']['Capabilities']();
}

export function CreateSession(arg1, arg2, arg3, arg4) {
  return window['go']['app']['RPCService']['CreateSession'](arg1, arg2, arg3, arg4);
}

export function CheckoutGitBranch(arg1, arg2, arg3) {
  return window['go']['app']['RPCService']['CheckoutGitBranch'](arg1, arg2, arg3);
}

export function CreateGitWorktree(arg1, arg2, arg3, arg4) {
  return window['go']['app']['RPCService']['CreateGitWorktree'](arg1, arg2, arg3, arg4);
}

export function DeleteGitBranch(arg1, arg2, arg3) {
  return window['go']['app']['RPCService']['DeleteGitBranch'](arg1, arg2, arg3);
}

export function GetTurnChanges(arg1) {
  return window['go']['app']['RPCService']['GetTurnChanges'](arg1);
}

export function GitBranches(arg1) {
  return window['go']['app']['RPCService']['GitBranches'](arg1);
}

export function Health() {
  return window['go']['app']['RPCService']['Health']();
}

export function ListProjects() {
  return window['go']['app']['RPCService']['ListProjects']();
}

export function ListSessions(arg1) {
  return window['go']['app']['RPCService']['ListSessions'](arg1);
}

export function LoadConversation(arg1) {
  return window['go']['app']['RPCService']['LoadConversation'](arg1);
}

export function OpenProject(arg1) {
  return window['go']['app']['RPCService']['OpenProject'](arg1);
}

export function RenameSession(arg1, arg2) {
  return window['go']['app']['RPCService']['RenameSession'](arg1, arg2);
}

export function ResolveApproval(arg1) {
  return window['go']['app']['RPCService']['ResolveApproval'](arg1);
}

export function SendMessage(arg1, arg2, arg3, arg4) {
  return window['go']['app']['RPCService']['SendMessage'](arg1, arg2, arg3, arg4);
}

export function SelectDirectory(arg1) {
  return window['go']['app']['RPCService']['SelectDirectory'](arg1);
}

export function Settings() {
  return window['go']['app']['RPCService']['Settings']();
}

export function UpdateSettings(arg1) {
  return window['go']['app']['RPCService']['UpdateSettings'](arg1);
}

export function UndoTurn(arg1) {
  return window['go']['app']['RPCService']['UndoTurn'](arg1);
}
